In [25]:
cd ~/gitproject/analytics/file/


/home/mani/gitproject/analytics/file


In [26]:
import pandas as pd

In [27]:
daily_engagement = pd.read_csv("daily_engagement_full.csv")

In [31]:
len(daily_engagement['acct'].unique())

1237

In [32]:
daily_engagement.head(3)

utc_date  acct registration_date subscription_start course_key  \
0  2014-11-05   448        2014-08-05         2014-11-05   ud359-nd   
1  2014-11-05   448        2014-08-05         2014-11-05   ud120-nd   
2  2014-11-05   448        2014-08-05         2014-11-05   ud651-nd   

  sibling_key               course_title  has_visited  total_minutes_visited  \
0       ud359      Intro to Data Science          0.0                    0.0   
1       ud120  Intro to Machine Learning          0.0                    0.0   
2       ud651       Data Analysis with R          0.0                    0.0   

   lessons_completed  projects_completed account_key  
0                0.0                 0.0  2257038596  
1                0.0                 0.0  2257038596  
2                0.0                 0.0  2257038596

In [33]:
print [i for i in range(100) if i%2==0 and i%3==0]

[0, 6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96]


In [34]:
import numpy as np

In [35]:
employment = np.array([
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076
])


In [36]:
countries = np.array([
    'Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
    'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
    'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
    'Belize', 'Benin', 'Bhutan', 'Bolivia',
    'Bosnia and Herzegovina'
])



In [37]:
def max_employ(country,employ):
    i = employ.argmax()
    return (countries[i],employ[i])

In [38]:
print countries[:]

['Afghanistan' 'Albania' 'Algeria' 'Angola' 'Argentina' 'Armenia'
 'Australia' 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain' 'Bangladesh'
 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bhutan' 'Bolivia'
 'Bosnia and Herzegovina']


In [39]:
print countries.dtype


|S22


In [40]:
len(countries)

20

In [41]:
print employment.dtype

float64


In [42]:
for i in countries:
    print "Examining country {}".format(i)

Examining country Afghanistan
Examining country Albania
Examining country Algeria
Examining country Angola
Examining country Argentina
Examining country Armenia
Examining country Australia
Examining country Austria
Examining country Azerbaijan
Examining country Bahamas
Examining country Bahrain
Examining country Bangladesh
Examining country Barbados
Examining country Belarus
Examining country Belgium
Examining country Belize
Examining country Benin
Examining country Bhutan
Examining country Bolivia
Examining country Bosnia and Herzegovina


In [17]:
len(employment)

20

In [18]:
for i in range(len(countries)):
    country = countries[i]
    country_employ = employment[i]
    print 'Country {} has employment {}'.format(country,country_employ)

Country Afghanistan has employment 55.70000076
Country Albania has employment 51.40000153
Country Algeria has employment 50.5
Country Angola has employment 75.69999695
Country Argentina has employment 58.40000153
Country Armenia has employment 40.09999847
Country Australia has employment 61.5
Country Austria has employment 57.09999847
Country Azerbaijan has employment 60.90000153
Country Bahamas has employment 66.59999847
Country Bahrain has employment 60.40000153
Country Bangladesh has employment 68.09999847
Country Barbados has employment 66.90000153
Country Belarus has employment 53.40000153
Country Belgium has employment 48.59999847
Country Belize has employment 56.79999924
Country Benin has employment 71.59999847
Country Bhutan has employment 58.40000153
Country Bolivia has employment 70.40000153
Country Bosnia and Herzegovina has employment 41.20000076


In [43]:
print employment.mean()
print employment.std()
print employment.max()
print employment.sum()


58.6850000385
9.33826911369
75.69999695
1173.70000077


In [44]:
[1,2,3]+[4,5,6]

[1, 2, 3, 4, 5, 6]

In [45]:
vector1=np.array([1,2,3])
vector2=np.array([4,5,6])

vector1+vector2


array([5, 7, 9])

In [46]:
vector1*3

array([3, 6, 9])

In [47]:
vector1&vector2

array([0, 0, 2])

In [48]:
vector1

array([1, 2, 3])

In [49]:
vector2

array([4, 5, 6])

In [53]:
female_completion = np.array([
    97.35583,  104.62379,  103.02998,   95.14321,  103.69019,
    98.49185,  100.88828,   95.43974,   92.11484,   91.54804,
    95.98029,   98.22902,   96.12179,  119.28105,   97.84627,
    29.07386,   38.41644,   90.70509,   51.7478 ,   95.45072
])

# Male school completion rate in 2007 for those 20 countries
male_completion = np.array([
     95.47622,  100.66476,   99.7926 ,   91.48936,  103.22096,
     97.80458,  103.81398,   88.11736,   93.55611,   87.76347,
    102.45714,   98.73953,   92.22388,  115.3892 ,   98.70502,
     37.00692,   45.39401,   91.22084,   62.42028,   90.66958
])

In [54]:
female_completion

array([  97.35583,  104.62379,  103.02998,   95.14321,  103.69019,
         98.49185,  100.88828,   95.43974,   92.11484,   91.54804,
         95.98029,   98.22902,   96.12179,  119.28105,   97.84627,
         29.07386,   38.41644,   90.70509,   51.7478 ,   95.45072])

In [56]:
total=female_completion+male_completion

In [57]:
total/2

array([  96.416025,  102.644275,  101.41129 ,   93.316285,  103.455575,
         98.148215,  102.35113 ,   91.77855 ,   92.835475,   89.655755,
         99.218715,   98.484275,   94.172835,  117.335125,   98.275645,
         33.04039 ,   41.905225,   90.962965,   57.08404 ,   93.06015 ])

In [59]:
def standardize_data(values):
    standardize_value = (values-values.mean())/values.std()
    return standardize_value

In [64]:
a=np.array([1,2,3,4,5])

In [65]:
b=np.array([False,False,True,True,True])

In [66]:
a[b]

array([3, 4, 5])

In [67]:
b>2

array([False, False, False, False, False], dtype=bool)

In [68]:
a[a>2]

array([3, 4, 5])